docs/blog/en/guide.md
```
<SourceClass>[text](url)</SourceClass>
```
=> New supported format of SourceClass component

.idea/GitLink.xml, .idea/swagger-settings.xml, evita_api/src/main/java/io/evitadb/api/requestResponse/extraResult/Histogram.java, evita_api/src/main/java/io/evitadb/api/requestResponse/extraResult/HistogramContract.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/cache/CacheableHistogram.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/cache/CacheableHistogramContract.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/producer/AttributeHistogramComputer.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/producer/PriceHistogramComputer.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/model/extraResult/HistogramDescriptor.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/resolver/dataFetcher/extraResult/AttributeHistogramsDataFetcher.java, evita_external_api/evita_external_api_grpc/server/src/main/java/io/evitadb/externalApi/grpc/builders/query/extraResults/GrpcHistogramBuilder.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcExtraResultsOuterClass.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcHistogram.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcHistogramOrBuilder.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/requestResponse/ResponseConverter.java, evita_external_api/evita_external_api_grpc/shared/src/main/resources/META-INF/io/evitadb/externalApi/grpc/GrpcExtraResults.proto, evita_functional_tests/src/test/java/io/evitadb/api/EntityByAttributeFilteringFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/CatalogGraphQLQueryEntityQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/grpc/builders/query/GrpcExtraResultsBuilderTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/grpc/builders/query/extraResults/GrpcHistogramBuilderTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/grpc/testUtils/GrpcAssertions.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/CatalogRestQueryEntityQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/CatalogRestUpsertEntityMutationFunctionalTest.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/cache/serializer/FlattenedHistogramComputerSerializer.java
This reverts commit dd0954347ca78194ade5c1533187f8e2902c6296.
=> revert(#414): "feat(#402): provide requested bucket count in result histogram DTO"

.github/workflows/docker-latest.yml
(cherry picked from commit a04a56e5722321d560bf489cc2326d7698e74490)
=> ci: attempt to deploy image per MAJOR version

evita_engine/src/main/java/io/evitadb/index/array/ComplexObjArrayChanges.java, evita_engine/src/main/java/io/evitadb/index/array/TransactionalComplexObjArray.java, evita_engine/src/main/java/io/evitadb/index/attribute/FilterIndex.java, evita_engine/src/main/java/io/evitadb/index/invertedIndex/InvertedIndex.java
Corrected hopefully last problems observed in logs.
=> Hotfix patch

evita_engine/src/main/java/io/evitadb/index/array/ComplexObjArrayChanges.java, evita_engine/src/main/java/io/evitadb/index/invertedIndex/InvertedIndex.java, evita_functional_tests/src/test/java/io/evitadb/index/invertedIndex/InvertedIndexTest.java
Added test and fixed the problem.
=> fix(#575): Histogram values are not monotonic in Inverted histogram

docker/README.MD, documentation/user/en/operate/configure.md, documentation/user/en/operate/run.md, evita_server/dist/run.sh, evita_server/run-server.sh, evita_server/src/main/java/io/evitadb/server/EvitaServer.java, evita_server/src/main/java/io/evitadb/server/yaml/EvitaConstructor.java, evita_server/src/main/java/io/evitadb/server/yaml/IncludeConstruct.java
The default configuration file moved from Docker image to classpath to avoid conflicts in YAML ordering.
=> fix(#577): Support for layering configuration

evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/producer/HierarchySet.java
(cherry picked from commit 77737738902b94e0dea9c1afb4a2b40ea1421523)
=> fix: ArrayIndexOutOfBounds error correction

documentation/user/en/operate/configure.md, evita_server/src/main/resources/evita-configuration.yaml, evita_test_support/src/main/resources/evita-configuration.yaml
=> fix(#654): remove CLI property for configuring evitaLab connections

documentation/user/en/operate/reference/metrics.md, evita_engine/src/main/java/io/evitadb/core/cache/payload/FlattenedFormulaWithFilteredPrices.java, evita_engine/src/main/java/io/evitadb/core/cache/payload/FlattenedFormulaWithFilteredPricesAndFilteredOutRecords.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/prefetch/EntityFilteringFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/prefetch/SelectionFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/FilteredPriceRecordAccessor.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/filteredPriceRecords/FilteredPriceRecords.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/priceIndex/PriceIdContainerFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/priceIndex/PriceIndexContainerFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/priceIndex/PriceListCombinationFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/termination/FirstVariantPriceTerminationFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/termination/PlainPriceTerminationFormulaWithPriceFilter.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/termination/SumPriceTerminationFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/translate/PriceIdToEntityIdTranslateFormula.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/AttributeHistogramTranslator.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/producer/AttributeHistogramProducer.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/producer/PriceHistogramComputer.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/producer/PriceHistogramProducer.java, evita_engine/src/main/java/io/evitadb/core/query/filter/translator/attribute/alternative/AttributeBitmapFilter.java, evita_engine/src/main/java/io/evitadb/core/query/filter/translator/entity/alternative/LocaleEntityToBitmapFilter.java, evita_engine/src/main/java/io/evitadb/core/query/filter/translator/price/alternative/SellingPriceAvailableBitmapFilter.java, evita_engine/src/main/java/io/evitadb/core/query/sort/OrderByVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/sort/price/FilteredPriceRecordsCollector.java, evita_engine/src/main/java/io/evitadb/core/query/sort/price/FilteredPricesSorter.java, evita_functional_tests/src/test/java/io/evitadb/core/query/sort/price/FilteredPriceRecordsCollectorTest.java, evita_performance_tests/src/main/java/io/evitadb/spike/FormulaCostMeasurement.java, evita_performance_tests/src/main/java/io/evitadb/spike/mock/MockEntityIdsFormula.java, evita_performance_tests/src/main/java/io/evitadb/spike/mock/MockInnerRecordIdsFormula.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/cache/serializer/FlattenedFormulaWithFilteredPricesAndFilteredOutRecordsSerializer.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/cache/serializer/FlattenedFormulaWithFilteredPricesSerializer.java
=> fix(#668): Filter was not yet called on selling price bitmap filter, this is not expected!

evita_external_api/evita_external_api_grpc/server/src/main/java/io/evitadb/externalApi/grpc/services/EvitaService.java, evita_external_api/evita_external_api_grpc/server/src/main/java/io/evitadb/externalApi/grpc/services/EvitaSessionService.java
Armeria doesn't copy the timeout to grpc context automatically. We need to get the proper timeout from the Armeria context directly.
=> fix: timeout was taken from the wrong context on the server side

.github/release-drafter.yml
=> ci(release-notes): better communicate changes in release notes. Refs: #758

evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/builder/constraint/ConstraintSchemaBuilder.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/constraint/DataLocatorResolver.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/resolver/constraint/ConstraintDescriptorResolver.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/builder/constraint/GraphQLConstraintSchemaBuilder.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/api/catalog/dataApi/builder/constraint/OpenApiConstraintSchemaBuilder.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/resolver/constraint/AbstractConstraintResolverTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/resolver/constraint/RequireConstraintResolverTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/resolver/constraint/AbstractConstraintResolverTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/resolver/constraint/RequireConstraintResolverTest.java, evita_query/src/main/java/io/evitadb/api/query/require/FacetGroupsConjunction.java, evita_query/src/main/java/io/evitadb/api/query/require/FacetGroupsDisjunction.java, evita_query/src/main/java/io/evitadb/api/query/require/FacetGroupsNegation.java, evita_test_support/src/main/java/io/evitadb/test/client/query/ConstraintToJsonConverterTest.java
=> fix: facetXXXGroupsXXXjunction constraint target reference entity type instead of reference group type

evita_engine/src/main/java/io/evitadb/core/query/sort/attribute/translator/PredecessorAttributeComparator.java
=> fix: NullPointerException in PredecessorAttributeComparator

evita_engine/src/main/java/io/evitadb/index/attribute/ChainIndex.java
The bug manifests itself by incorrect predecessor value in `io.evitadb.index.attribute.ChainIndex#elementStates` comparing to real value stored in entity data. It seems that during consolidations predecessor of different element is stored to the state of discussed element. Unfortunatelly, the logic is quite complex and there are many cases where the state is updated with different values so it doesn't make sense to encapsulate inner map into more complex object because we'd still rely on proper inputs during updates.
Refs: https://github.com/FgForrest/evitaDB/issues/786
=> fix: ChainIndex corrupted in consolidation

documentation/user/en/query/requirements/examples/facet/facet-groups-conjunction.graphql, documentation/user/en/query/requirements/examples/facet/facet-groups-conjunction.rest, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/builder/constraint/ConstraintSchemaBuilder.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/resolver/constraint/ConstraintResolver.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/builder/constraint/GraphQLConstraintSchemaBuilder.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/api/catalog/dataApi/builder/constraint/OpenApiConstraintSchemaBuilder.java, evita_test_support/src/main/java/io/evitadb/test/client/query/ConstraintToJsonConverter.java
=> fix: cannot use facetXXXGroupsXXX for reference without group type (i.e. with no parameters)

evita_api/src/main/java/io/evitadb/api/CatalogContract.java, evita_engine/src/main/java/io/evitadb/core/Catalog.java, evita_engine/src/main/java/io/evitadb/core/CatalogConsumerControl.java, evita_engine/src/main/java/io/evitadb/core/CatalogConsumersListener.java, evita_engine/src/main/java/io/evitadb/core/CorruptedCatalog.java, evita_engine/src/main/java/io/evitadb/core/Evita.java, evita_engine/src/main/java/io/evitadb/core/EvitaSession.java, evita_engine/src/main/java/io/evitadb/core/SessionRegistry.java, evita_engine/src/main/java/io/evitadb/store/spi/CatalogPersistenceService.java, evita_engine/src/main/java/io/evitadb/store/spi/StoragePartPersistenceService.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/OffsetIndex.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/CatalogOffsetIndexStoragePartPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultCatalogPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultEntityCollectionPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/ObsoleteFileMaintainer.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/OffsetIndexStoragePartPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/serializer/CatalogHeaderSerializer.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/task/BackupTask.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/wal/TransactionalStoragePartPersistenceService.java
=> fix: Data files might have been removed before backup is finished

evita_functional_tests/src/test/java/io/evitadb/api/EvitaTest.java
=> test: added test for problematic scenario

.github/workflows/ci-master.yml, .github/workflows/ci-release.yml, .github/workflows/docker-latest.yml
We need to set up new release workflow so that it's triggerred by GitHub on master branch.
=> build: attempt to fix release workflow

.github/workflows/ci-master.yml
Failed to execute goal on project evita_query: Could not resolve dependencies for project io.evitadb:evita_query:jar:2025.2-SNAPSHOT
=> build: attempt to correct build

evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/resolver/constraint/FacetSummaryResolver.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/resolver/dataFetcher/QueryEntitiesDataFetcher.java
The attribute resolved was trying to find attributes in reference entity type instead of reference group type.
Refs: #885
=> fix(graphql): group entity in facet summary cannot resolve correct attributes

evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/builder/constraint/ConstraintSchemaBuilder.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/resolver/constraint/ConstraintDescriptorResolver.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/builder/constraint/GraphQLConstraintSchemaBuilder.java, evita_functional_tests/src/test/java/io/evitadb/api/query/descriptor/ConstraintProcessorTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/CatalogGraphQLListEntitiesQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/CatalogGraphQLQueryEntityQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/CatalogRestListEntitiesQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/CatalogRestQueryEntityQueryFunctionalTest.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintDescriptor.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintDescriptorProvider.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintProcessor.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/annotation/ConstraintSupportedValues.java, evita_query/src/main/java/io/evitadb/api/query/order/AttributeNatural.java
=> fix(api): cannot sort by sortable attribute compounds in GQL and REST APIs
