FgForrest/evitaDB

docker/evita-configuration.yaml, docs/user/en/operate/configure.md, evita_api/src/main/java/io/evitadb/api/configuration/ServerOptions.java, evita_api/src/main/java/io/evitadb/api/exception/ReadOnlyException.java, evita_engine/src/main/java/io/evitadb/core/Evita.java, evita_functional_tests/src/test/java/io/evitadb/core/ReadOnlyEvitaTest.java, evita_test_support/src/main/resources/evita-configuration.yaml
We want to open access to our test dataset directly on https://evitadb.io for all to play. In order to avoid server / catalog pollution we want to allow read-only access. Until https://github.com/FgForrest/evitaDB/issues/25 is finalized we plan to add simple boolean flag that will start the server in full read-only mode that doesn't allow clients to:
- create / update / delete catalog schemas
- open read-write sessions
This will effectively mean that the clients would not be able to alter the demo data and can only play with read queries.
=> feat(#44): support for read-only mode

evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultCatalogPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/schema/serializer/CatalogSchemaSerializer.java
The caller code wraps the result into an optional and exception is not expected.
=> fix: when schema is not found exception must not be thrown

evita_store/evita_store_server/src/main/java/io/evitadb/store/index/serializer/GlobalUniqueIndexStoragePartSerializer.java
The serialized value is always a plain type, but the value read was array type which caused CorruptedRecordException.
=> fix: corrected GlobalUniqueIndexSerializer for array types

evita_external_api/evita_external_api_rest/pom.xml, pom.xml
- Swagger: 2.2.2 -> 2.2.15
Ensured that new version of Jackson is enforced for Swagger.
=> build: upgraded versions of the libraries evitaDB depends on

evita_api/src/main/java/io/evitadb/api/ClientContext.java
It seems that using the InheritableThreadLocal in multithreaded GraphQL / gRPC environment wasn't a good idea.
=> fix: removing hotfix for context pop

docker/evita-configuration.yaml, documentation/user/en/operate/configure.md, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/configuration/AbstractApiConfiguration.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/configuration/ApiOptions.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/http/ExternalApiServer.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/configuration/GraphQLConfig.java, evita_external_api/evita_external_api_grpc/server/src/main/java/io/evitadb/externalApi/grpc/configuration/GrpcConfig.java, evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/LabManager.java, evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/api/LabApiBuilder.java, evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/api/builder/LabApiBuildingContext.java, evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/configuration/LabConfig.java, evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/gui/resolver/GuiHandler.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/RestManager.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/RestProviderRegistrar.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/api/builder/RestBuildingContext.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/api/catalog/CatalogRestBuilder.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/api/catalog/builder/CatalogRestBuildingContext.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/api/system/SystemRestBuilder.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/api/system/builder/SystemRestBuildingContext.java, evita_external_api/evita_external_api_rest/src/main/java/io/evitadb/externalApi/rest/configuration/RestConfig.java, evita_external_api/evita_external_api_system/src/main/java/io/evitadb/externalApi/system/SystemProvider.java, evita_external_api/evita_external_api_system/src/main/java/io/evitadb/externalApi/system/SystemProviderRegistrar.java, evita_external_api/evita_external_api_system/src/main/java/io/evitadb/externalApi/system/configuration/SystemConfig.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/openApi/SchemaUtilsTest.java, evita_performance_tests/src/main/java/io/evitadb/performance/externalApi/graphql/artificial/GraphQLArtificialFullDatabaseBenchmarkState.java, evita_performance_tests/src/main/java/io/evitadb/performance/externalApi/grpc/artificial/GrpcArtificialFullDatabaseBenchmarkState.java, evita_performance_tests/src/main/java/io/evitadb/performance/externalApi/javaDriver/artificial/JavaDriverArtificialFullDatabaseBenchmarkState.java, evita_performance_tests/src/main/java/io/evitadb/performance/externalApi/rest/artificial/RestArtificialFullDatabaseBenchmarkState.java, evita_test_support/src/main/java/io/evitadb/test/extension/EvitaParameterResolver.java, evita_test_support/src/main/resources/evita-configuration.yaml
The host name for all APIs is by default the host name of the system evitaDB is running on. Unfortunately, when evitaDB starts in a Docker container, the host system is a virtual system of the Docker host and neither the host name (nor the ports) matches the host system the developer is working with (unless the `--net=host` parameter is used, which doesn't work on Windows and Mac OS).
That's why we need an additional configuration property for each API that allows to propagate the name of the external system to the evitaDB instance, so that it could be used for generating links in Open API schemas and evitaLab.
=> feat(#299): Allow to override host name the evitaDB uses

evita_api/src/main/java/io/evitadb/api/requestResponse/schema/CatalogSchemaContract.java, evita_api/src/main/java/io/evitadb/api/requestResponse/schema/mutation/reference/CreateReferenceSchemaMutation.java, evita_api/src/main/java/io/evitadb/api/requestResponse/schema/mutation/reference/ModifyReferenceSchemaRelatedEntityGroupMutation.java, evita_api/src/main/java/io/evitadb/api/requestResponse/schema/mutation/reference/ModifyReferenceSchemaRelatedEntityMutation.java, evita_functional_tests/src/test/java/io/evitadb/core/EvitaTest.java
Former implementation allowed to create reference targeting non-existing evitaDB entity type.
=> fix(#162): add validation for managed entity references

evita_engine/src/main/java/io/evitadb/core/query/extraResult/ExtraResultPlanningVisitor.java, evita_functional_tests/src/test/java/io/evitadb/api/EntityByChainOrderingFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/api/EntityByFacetFilteringFunctionalTest.java
When attribute of `Predecessor` type is used to sort facet statistics, evitaDB doesn't sort the facet statistics within groups.
```
query(
collection('Product'),
filterBy(
entityLocaleEquals('cs')
),
require(
page(1, 20),
facetSummaryOfReference(
'groups',
COUNTS,
orderBy(
attributeNatural('order', ASC)
),
entityFetch(
attributeContent('name', "order"),
dataInLocales('cs')
)
)
)
)
```
Other string attributes work as expected.
=> fix(#393): Predecessor ordering used in facet statistics doesn't work

evita_engine/src/main/java/io/evitadb/core/query/algebra/base/AndFormula.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/histogram/producer/AttributeHistogramProducer.java, evita_functional_tests/src/test/java/io/evitadb/api/EntityByAttributeFilteringFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/driver/EvitaClientTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/CatalogRestQueryEntityQueryFunctionalTest.java
In demo dataset when `attributeHistogram` is requested with `attributeBetween` in a `userFilter`:
```
query(
collection("Product"),
filterBy(
userFilter(
attributeBetween("battery-capacity", "3000", "7000")
)
),
require(
attributeHistogram(10, "battery-capacity")
)
)
```
evitaDB returns NPE:
```
Caused by: java.lang.NullPointerException: null
at java.base/java.util.Comparator.lambda$comparingLong$6043328a$1(Comparator.java:515)
at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
at java.base/java.util.TimSort.sort(TimSort.java:220)
at java.base/java.util.Arrays.sort(Arrays.java:1307)
at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
at …
```
=> fix(#401): NPE when using attributeBetween for attributeHistogram

evita_api/src/main/java/io/evitadb/api/proxy/impl/entityBuilder/SetReferenceMethodClassifier.java
I have method declaration:
```java
@ReferenceRef(REFERENCE_PARAMETER_VALUES)
@CreateWhenMissing
void addOrUpdateParameterValue(
int parameterValueId,
@Nonnull Consumer<PublishedProductParameterValueEditor> parameterValueConsumer
) throws ContextMissingException;
```
And after calling this method the reference is not created and updated.
=> fix(#435): OEM proxy implementation fails to add reference to an entity

evita_api/src/main/java/io/evitadb/api/proxy/impl/SealedEntityProxyState.java, evita_api/src/main/java/io/evitadb/api/requestResponse/data/structure/ExistingEntityBuilder.java
In certain scenarios - namely this signature:
```java
product.addOrUpdateStock(
stock.getIdCatalogEntity(),
thatIs -> thatIs.setQuantityOnStock(quantity)
);
```
The resulting mutation may lack `InsertReferenceMutation`. The problem is caused by invalid usage of `ExistingReferenceBuilder` for scenarios where `InitialReferenceBuilder` should be used (because there is no such reference in the `ExistingEntityBuilder` base entity that is being modified).
=> fix(#445): Reference mutations set via OEM might be incomplete

evita_common/src/main/java/io/evitadb/dataType/data/ComplexDataObjectConverter.java, evita_common/src/main/java/io/evitadb/dataType/data/ComplexDataObjectToJsonConverter.java, evita_engine/src/main/java/io/evitadb/core/query/QueryContext.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/AbstractFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/utils/visitor/FormulaCloner.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/ExtraResultPlanningVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/facet/producer/AbstractFacetFormulaGenerator.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/facet/producer/FacetFormulaGenerator.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/facet/producer/ImpactFormulaGenerator.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/facet/producer/MutableFormula.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/visitor/ChildrenStatisticsHierarchyVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/visitor/ParentStatisticsHierarchyVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/utils/AbstractFormulaStructureOptimizeVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/filter/FilterByVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/filter/translator/price/PriceListCompositionTerminationVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/sort/OrderByVisitor.java, evita_engine/src/main/java/io/evitadb/index/transactionalMemory/TransactionalMemory.java, evita_performance_tests/src/main/java/io/evitadb/performance/client/state/ClientSyntheticTestState.java, evita_query/src/main/java/io/evitadb/api/query/visitor/ConstraintCloneVisitor.java, evita_query/src/main/java/io/evitadb/api/query/visitor/QueryPurifierVisitor.java
The optimization is done by compromising our approach to formula immutability. In this case, I introduce a new special `MutableFormula` that delegates calls to inner formulas that can be swapped. This way we can fully reuse the formula tree for multiple invocations and only replace bitmaps with primary keys referencing specific facets, thus avoiding an awful lot of repeated formula reconstructions.
=> perf(#464): Slow facet summary formula generation

evita_engine/src/main/java/io/evitadb/core/SessionRegistry.java, evita_engine/src/main/java/io/evitadb/core/query/QueryContext.java, evita_engine/src/main/java/io/evitadb/core/query/QueryPlanner.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/prefetch/PrefetchFormulaVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/ExtraResultPlanningVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/facet/FacetSummaryOfReferenceTranslator.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/facet/producer/FacetSummaryProducer.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/HierarchyOfReferenceTranslator.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/HierarchyOfSelfTranslator.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/producer/HierarchySet.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/producer/HierarchyStatisticsProducer.java, evita_engine/src/main/java/io/evitadb/core/query/sort/NestedContextSorter.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/http/ExternalApiExceptionHandler.java
Query that used prefetch evaluation logic revealed that sorters in extra result producers - namely facet summary and hierarchy summary stick to the original query context. This resulted in incorrect sorting implementation which tried to locate entities of invalid type in original queried entity query context, which provided unexpected NULL value.
=> fix(#471): Extra results sorter does not carry the correct query context

evita_engine/src/main/java/io/evitadb/core/EntityCollection.java
The code was updated to add a condition that checks if the requested locale is contained within the entity's locales while fetching the entity by its primary key. If the locale is not present, the function will now return null.
=> fix(#480): GraphQL returns errors when fetching referenced entities in a locale they don't have

evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/facet/producer/ImpactFormulaGenerator.java, evita_engine/src/main/java/io/evitadb/core/query/filter/translator/facet/FacetHavingTranslator.java
This bug was introduced by https://github.com/FgForrest/evitaDB/issues/464
For this query the facet group conjunction the query:
```
query(
collection("Product"),
filterBy(
userFilter(
facetHaving(
"groups",
entityHaving(
attributeInSet("code", "sale")
)
)
)
),
require(
facetSummaryOfReference(
"groups",
IMPACT,
entityFetch(attributeContent("code"))
),
facetGroupsConjunction("groups")
)
)
```
Is not properly recognized and default disjunction logic is used instead.
=> fix(#482): Facet group conjunction is ignored

evita_engine/src/main/java/io/evitadb/core/query/filter/FilterByVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/filter/translator/attribute/alternative/AttributeBitmapFilter.java
NullpointerException leaked into the code - obviously the `TriFunction` may return null.
```
2024-03-19T14:04:07.121221777Z 14:04:07.120 ERROR i.e.c.SessionRegistry CID: RID: - Unexpected internal Evita error occurred: Cannot invoke "java.util.stream.Stream.anyMatch(java.util.function.Predicate)" because "attrStream" is null
2024-03-19T14:04:07.121255657Z java.lang.NullPointerException: Cannot invoke "java.util.stream.Stream.anyMatch(java.util.function.Predicate)" because "attrStream" is null
2024-03-19T14:04:07.121261277Z 	at io.evitadb.core.query.filter.translator.attribute.AttributeInRangeTranslator.lambda$getDateTimeRangePredicate$4(AttributeInRangeTranslator.java:152)
2024-03-19T14:04:07.121265897Z 	at io.evitadb.core.query.filter.translator.attribute.alternative.AttributeBitmapFilter …
```
=> fix(#495): NPE in AttributeBitmap calculation

evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/builder/constraint/ConstraintSchemaBuilder.java, evita_functional_tests/src/test/java/io/evitadb/api/query/descriptor/ConstraintDescriptorProviderTest.java, evita_functional_tests/src/test/java/io/evitadb/api/query/descriptor/ConstraintProcessorTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/CatalogGraphQLQueryEntityQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/CatalogRestQueryEntityQueryFunctionalTest.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintDescriptor.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintDescriptorProvider.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintNullabilitySupport.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintProcessor.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/annotation/ConstraintSupportedValues.java, evita_query/src/main/java/io/evitadb/api/query/filter/AttributeIs.java
To support this new tooling was created for handling nullability support in constraints in general.
=> feat(#498): don't allow attributeIs constraint for nonnull attributes

evita_engine/src/main/java/io/evitadb/core/query/sort/price/FilteredPricesSorter.java, evita_functional_tests/src/test/java/io/evitadb/api/CombinedPriceEntityByPriceFilteringFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/api/EntityByPriceFilteringFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/api/FindFirstPriceEntityByPriceFilteringFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/api/SumPriceEntityByPriceFilteringFunctionalTest.java
Added tests proving the reported issue and corrected error in end index computation and unsorted result appending.
=> fix(#520): Non-first page of entities empty when ordering by price

evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/facet/FilterFormulaFacetOptimizeVisitor.java, evita_functional_tests/src/test/java/io/evitadb/api/EntityByFacetFilteringFunctionalTest.java
When UserFilterFormula was not part of the computational tree, the facet impact computation didn't work well.
=> fix(#537): Incorrect facet statistics difference when userFilter is used

evita_engine/src/main/java/io/evitadb/core/EntityCollection.java, evita_engine/src/main/java/io/evitadb/core/query/QueryContext.java, evita_engine/src/main/java/io/evitadb/core/query/ReferencedEntityFetcher.java
When the entity is fetched from the data store, it's entity body storage part is always fetched twice. This becomes a problem when a large number of entities are fetched from the data store, and when the OS file cache is cold, it can mean twice the latency. This fetching is not entirely necessary if we refactor the `enrichEntity` method into two separate ones and call the second one only conditionally.
=> perf(#559): Entity fetching optimization

evita_engine/src/main/java/io/evitadb/ConsistencySensitiveDataStructure.java, evita_engine/src/main/java/io/evitadb/index/attribute/ChainIndex.java, evita_functional_tests/src/test/java/io/evitadb/index/attribute/ChainIndexTest.java
We need to write better fuzzy tests that would allow us to exterminate the edge cases in the ChainIndex. It seems that the real production systems may behave sometimes chaotically till they return back to consistent state.
=> fix(#531): Random errors and NullPointerExceptions in ChainIndex

docker/Dockerfile, docker/entrypoint.sh, evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/configuration/GuiConfig.java, evita_functional_tests/src/test/java/io/evitadb/server/EvitaServerTest.java, evita_functional_tests/src/test/resources/testData/evita-configuration-one.yaml, evita_functional_tests/src/test/resources/testData/evita-configuration-two.yaml, evita_server/src/main/java/io/evitadb/server/EvitaServer.java, evita_test_support/src/main/java/io/evitadb/test/EvitaTestSupport.java
In complex build pipelines it's not easy to set up all evitaDB parameters in one shot. It would be helpful if we could layer the `evita-configuration.yml` so that we first load the full configuration with defaults and then apply shorter versions that override only part of those settings. The overriding configurations could be expected to be in the same folder as the default configuration and could be applied in alphabetical order - i.e:
1. evita-configuration.yml
2. evita-configuration-environment.yml
3. evita-configuration-project.yml
=> fix(#577): Support for layering configuration

evita_engine/src/main/java/io/evitadb/core/query/algebra/base/NotFormula.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/facet/UserFilterFormula.java
Error occurred on our test system:
```
2024-05-30T05:02:40.171480900Z SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@66e3d4d9
2024-05-30T05:02:40.171486100Z io.evitadb.exception.GenericEvitaInternalError: Formula results haven't been computed!
2024-05-30T05:02:40.171489959Z 	at io.evitadb.utils.Assert.isPremiseValid(Assert.java:89)
2024-05-30T05:02:40.171493839Z 	at io.evitadb.core.query.algebra.AbstractFormula.getCost(AbstractFormula.java:127)
2024-05-30T05:02:40.171497789Z 	at java.base/java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:231)
2024-05-30T05:02:40.171501369Z 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) …
```
=> fix: Formula results haven't been computed!

evita_api/src/main/java/io/evitadb/api/exception/TransactionException.java, evita_common/src/main/java/io/evitadb/dataType/array/CompositeObjectArray.java, evita_common/src/main/java/io/evitadb/utils/FileUtils.java, evita_engine/src/main/java/io/evitadb/core/Catalog.java, evita_engine/src/main/java/io/evitadb/core/transaction/stage/AbstractTransactionStage.java, evita_engine/src/main/java/io/evitadb/core/transaction/stage/ConflictResolutionTransactionStage.java, evita_engine/src/main/java/io/evitadb/core/transaction/stage/TrunkIncorporationTransactionStage.java, evita_engine/src/main/java/io/evitadb/core/transaction/stage/WalAppendingTransactionStage.java, evita_functional_tests/src/test/java/io/evitadb/api/EvitaTransactionalFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/store/wal/CatalogWriteAheadLogIntegrationTest.java, evita_functional_tests/src/test/java/io/evitadb/store/wal/CatalogWriteAheadLogTest.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/kryo/ObservableOutputKeeper.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/OffsetIndex.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/io/WriteOnlyFileHandle.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/io/WriteOnlyOffHeapWithFileBackupHandle.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultCatalogPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/wal/CatalogWriteAheadLog.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/wal/supplier/AbstractMutationSupplier.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/wal/supplier/MutationSupplier.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/wal/supplier/TransactionLocations.java
It seems that when the catalog file exceeds the threshold size (100MB by default) and is compressed into a new file, it's somehow corrupted. The previous file is not deleted, but partially overwritten, and the new file is also corrupted. This was discovered by analyzing file remnants where the original file was much smaller than the 100MB it should have been, and the contents were completely corrupted. It is likely that different tasks are writing to corrupted versions of the file. We need to investigate this issue and write a more complex integration test for this scenario.
=> fix(#590): Catalog data file gets broken after compaction

evita_common/src/main/java/io/evitadb/utils/NumberUtils.java, evita_engine/src/main/java/io/evitadb/index/attribute/SortIndex.java, evita_engine/src/main/java/io/evitadb/index/attribute/SortIndexChanges.java, evita_engine/src/main/java/module-info.java, evita_functional_tests/src/test/java/io/evitadb/index/attribute/SortIndexTest.java, evita_functional_tests/src/test/java/io/evitadb/utils/NumberUtilsTest.java
SortIndex internally holds Map, where key is the indexed value and value is the cardinality of the key. There is a normalizer implementation for certain types of keys (localized strings), but not for BigDecimal. But when the indexed values are BigDecimals and come in different forms - like `0` and `0.000` - they don't match in the map lookup unless normalized by `stripTrailingZeros()`. This causes the sort index to break during indexing.
=> fix(611): SortIndex handles BigDecimal in wrong way

evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/gui/resolver/GuiHandler.java
lab gui handler windows fix - path standardized inside of jar to forward slashes on all systems si
=> fix: lab gui handler windows fix - path standardized inside of jar to forward slashes on all systems si

evita_engine/src/main/java/io/evitadb/core/Evita.java, evita_engine/src/main/java/io/evitadb/core/async/ObservableExecutorServiceWithHardDeadline.java, evita_engine/src/main/java/io/evitadb/core/async/ObservableThreadExecutor.java, evita_engine/src/main/java/io/evitadb/core/async/Scheduler.java, evita_external_api/evita_external_api_grpc/client/src/main/java/io/evitadb/driver/EvitaClient.java, evita_external_api/evita_external_api_grpc/client/src/main/java/io/evitadb/driver/EvitaClientManagement.java, evita_external_api/evita_external_api_grpc/client/src/main/java/io/evitadb/driver/EvitaClientSession.java, evita_external_api/evita_external_api_grpc/client/src/main/java/io/evitadb/driver/StubTimeoutProxy.java, evita_external_api/evita_external_api_grpc/server/src/main/java/io/evitadb/externalApi/grpc/services/EvitaManagementService.java, evita_external_api/evita_external_api_grpc/server/src/main/java/io/evitadb/externalApi/grpc/services/EvitaService.java, evita_external_api/evita_external_api_grpc/server/src/main/java/io/evitadb/externalApi/grpc/services/EvitaSessionService.java, evita_functional_tests/src/test/java/io/evitadb/driver/EvitaClientReadOnlyTest.java, evita_functional_tests/src/test/java/io/evitadb/driver/EvitaClientReadWriteTest.java, evita_functional_tests/src/test/java/io/evitadb/server/EvitaServerTest.java
There are some operations that may take quite a while - for example replacing `goLive` operation (which reloads entire catalog in memory) or (`replaceCatalog`). These operations randomly times out when executed from gRPC client because the client and server timeouts are not aligned and either of those might cancel the operation any time.
=> fix(#717): Client and server timeouts are not aligned

evita_common/src/main/java/io/evitadb/utils/NumberUtils.java, evita_engine/src/main/java/io/evitadb/core/query/algebra/price/predicate/PricePredicate.java, evita_engine/src/main/java/io/evitadb/core/query/filter/translator/price/alternative/SellingPriceAvailableBitmapFilter.java, evita_engine/src/main/java/io/evitadb/index/mutation/index/PriceIndexMutator.java, evita_functional_tests/src/test/java/io/evitadb/utils/NumberUtilsTest.java
Currently evitaDB fails with an exception when the client tries to index the price `243.2405` with 2 decimal places because there is a remainder `.0005`. This is rather impractical, so evitaDB should automatically round the remainder and include it in the converted integer. The original values on the entity remain in the original form - i.e. in BigDecimal without loss of precision. This rounding and conversion to int only happens when the entity is indexed for filtering/searching.
=> fix(#726): automatic rounding for attributes prices with incompatible number of decimal places

evita_engine/src/main/java/io/evitadb/core/query/QueryPlanner.java, evita_engine/src/main/java/io/evitadb/core/query/QueryPlanningContext.java, evita_engine/src/main/java/io/evitadb/core/query/ReferencedEntityFetcher.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/AbstractHierarchyTranslator.java, evita_engine/src/main/java/io/evitadb/core/query/extraResult/translator/hierarchyStatistics/producer/ParentStatisticsComputer.java, evita_engine/src/main/java/io/evitadb/core/query/filter/FilterByVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/filter/translator/reference/EntityHavingTranslator.java, evita_engine/src/main/java/io/evitadb/index/hierarchy/predicate/FilteringFormulaHierarchyEntityPredicate.java
- fix(#731): When target hierarchical entity is not found, parents should return empty result instead of error
- fix(#732): EntityPrimaryKeyInSet pollutes query execution context
=> fix: cumulative patch

evita_api/src/main/java/io/evitadb/api/requestResponse/data/structure/ExistingPricesBuilder.java
The `io.evitadb.api.requestResponse.data.structure.ExistingPricesBuilder` in `buildChangeSet` method, when `removeAllNonModifiedPrices` is set to true doesn't filter the original prices by `Droppable::exists` which leads to creating `RemovePriceMutation` for already removed prices and results in rejecting entity upsert.
(cherry picked from commit 5a3e2e7e60871cddc3d6c143bd2fd30ac25c27bc)
=> fix(#734): When prices are completely reset on an existing entity, removal mutation for already dropped price might be generated

documentation/user/en/operate/configure.md, evita_api/src/main/java/io/evitadb/api/configuration/StorageOptions.java, evita_functional_tests/src/test/java/io/evitadb/api/EvitaTransactionalFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/store/catalog/DefaultCatalogPersistenceServiceTest.java, evita_functional_tests/src/test/java/io/evitadb/store/catalog/DefaultIsolatedWalServiceTest.java, evita_functional_tests/src/test/java/io/evitadb/store/offsetIndex/OffsetIndexSerializationServiceTest.java, evita_functional_tests/src/test/java/io/evitadb/store/offsetIndex/OffsetIndexTest.java, evita_functional_tests/src/test/java/io/evitadb/store/offsetIndex/io/WriteOnlyOffHeapWithFileBackupHandleTest.java, evita_functional_tests/src/test/java/io/evitadb/store/wal/CatalogWriteAheadLogIntegrationTest.java, evita_server/src/main/resources/evita-configuration.yaml, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/OffsetIndex.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/io/WriteOnlyFileHandle.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/io/WriteOnlyOffHeapWithFileBackupHandle.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/model/VersionedValue.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/CatalogOffsetIndexStoragePartPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultCatalogPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultEntityCollectionPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/wal/TransactionalStoragePartPersistenceService.java, evita_test_support/src/main/resources/evita-configuration.yaml
Explicit file system synchronisation (java.io.FileDescriptor#sync) is an expensive operation that is not necessary in all scenarios. It ensures that committed data is safely written to persistent storage, but in integration testing, for example, this kind of guarantee is useless.
The measured impact of this explicit synchronisation in a test integration suite of 1400 E2E tests heavily using evitaDB resulted in 25% better performance (shorter test suite duration), which is a significant improvement. So it's a good idea to make this fsync a configurable option, enabled by default, but able to be disabled.
Refs: #767
=> feat: Make fsSync configurable

documentation/user/en/operate/configure.md, evita_api/src/main/java/io/evitadb/api/configuration/StorageOptions.java, evita_server/src/main/resources/evita-configuration.yaml, evita_test_support/src/main/resources/evita-configuration.yaml
Although time travel works on its own, we've found that it's impractical to use in production because it takes up too much disk space. These issues need to be addressed first so that this feature doesn't cause problems on production systems:
- https://github.com/FgForrest/evitaDB/issues/760
- https://github.com/FgForrest/evitaDB/issues/421
- https://github.com/FgForrest/evitaDB/issues/761
That's why we temporarily disable this feature in the default settings.
Refs: #772
=> chore: set time travel to disabled by default

evita_engine/src/main/java/io/evitadb/core/query/sort/CacheableSorter.java, evita_engine/src/main/java/io/evitadb/core/query/sort/DeferredSorter.java, evita_engine/src/main/java/io/evitadb/core/query/sort/attribute/MergedSortedRecordsSupplier.java
=> fix: ArrayIndexOutOfBounds in MergedSortedRecordsSupplier

evita_engine/src/main/java/io/evitadb/index/attribute/ChainIndex.java
The bug manifests itself by incorrect predecessor value in `io.evitadb.index.attribute.ChainIndex#elementStates` comparing to real value stored in entity data. It seems that during consolidations predecessor of different element is stored to the state of discussed element. Unfortunatelly, the logic is quite complex and there are many cases where the state is updated with different values so it doesn't make sense to encapsulate inner map into more complex object because we'd still rely on proper inputs during updates.
Refs: #786
=> fix: ChainIndex corrupted in consolidation

evita_engine/src/main/java/io/evitadb/core/query/sort/OrderByVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/sort/ReferenceOrderByVisitor.java, evita_engine/src/main/java/io/evitadb/core/query/sort/translator/OrderInScopeTranslator.java
This graphQL query:
```graphql
query productPage {
queryProduct{
recordStrip(limit: 1) {
data {
primaryKey
categories(
orderBy: {inScope: {scope: LIVE, ordering: {attributeCategoryPriorityNatural: ASC}}}
) {
referencedPrimaryKey
attributes {
categoryPriority
}
referencedEntity {
primaryKey
attributes {
code
}
}
}
}
}
}
}
```
... doesn't work properly. When ordering constraint is enveloped in `inScope` container it's completely skipped.
Refs: #789
=> fix: Ordering referenced entities by reference attribute inside `inScope` container doesn't work

docker/Dockerfile, docker/README.MD, docker/entrypoint.sh, documentation/user/en/get-started/run-evitadb.md, documentation/user/en/operate/run.md, evita_functional_tests/src/test/java/io/evitadb/server/EvitaServerTest.java, evita_functional_tests/src/test/java/io/evitadb/server/SpecialConfigInputFormatsHandlerTest.java, evita_functional_tests/src/test/resources/testData/evita-configuration-unknown-props.yaml, evita_server/src/main/java/io/evitadb/server/EvitaServer.java, evita_server/src/main/java/io/evitadb/server/yaml/AbstractClassDeserializer.java, evita_server/src/main/java/io/evitadb/server/yaml/SpecialConfigInputFormatsHandler.java, evita_server/src/main/java/io/evitadb/server/yaml/UnknownPropertyProblemHandler.java, evita_server/src/main/java/module-info.java
Actually, evitaDB fails to start if configuration contains unknown property (settings). This brings complications for "operations" guys who manage the configuration templates and don't always control the engine version actually used (they might apply newer configuration settings for older engine version). New default mode should be that unknown properties and container objects are ignored and only a warning is printed when the engine is started. If the engine is run with special `strict` mode, the engine will fail (current behaviour).
Refs: #806
=> feat: Allow engine start even if configuration contains unknown property

documentation/user/en/operate/observe.md, documentation/user/en/query/header/label.md, evita_api/src/main/java/io/evitadb/api/observability/trace/TracingContext.java, evita_engine/src/main/java/io/evitadb/core/async/ObservableThreadExecutor.java, evita_engine/src/main/java/io/evitadb/core/traffic/TrafficRecordingEngine.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/trace/TracingDecorator.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/utils/ExternalApiTracingContext.java, evita_external_api/evita_external_api_observability/src/main/java/io/evitadb/externalApi/observability/trace/JsonApiTracingContext.java
Adding labels directly into the query might be problem in Node.js environment due to the use of query templates, but it would be quite easy to add them to the HTTP request as headers. So we should be able to optionally accept query labels in headers in the form of:
- `X-Forwarded-Uri`: as the original URI requested for the frontend facade
- `X-Meta-Label`: with arbitrary value for new labels passed in headers
These headers should be automatically accepted and incorporated in the traffic recording.
Refs: #802
=> feat: Accept labels in HTTP headers

evita_common/src/main/java/io/evitadb/utils/VersionUtils.java, evita_functional_tests/src/test/java/io/evitadb/utils/VersionUtilsTest.java
=> fix: added tests and fixed invalid comparison

evita_engine/src/main/java/io/evitadb/core/query/ReferencedEntityFetcher.java
In case there are multiple scopes used in the query and references are fetched, some of them may be missing since previous formula was forgotten to be included in the aggregated result formula.
Refs: #830
=> fix: formula for previous scope was not included in aggregated formula

evita_engine/src/main/java/io/evitadb/core/query/sort/attribute/translator/ReferencePropertyTranslator.java, evita_engine/src/main/java/io/evitadb/index/hierarchy/HierarchyIndex.java, evita_engine/src/main/java/io/evitadb/index/hierarchy/HierarchyIndexContract.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/EvitaManagementServiceGrpc.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/EvitaServiceGrpc.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/EvitaSessionServiceGrpc.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcEntity.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcEnums.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcEvitaTrafficRecordingServiceGrpc.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcFacetGroupRelationLevel.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcFacetRelationType.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcOffsetAndLimit.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcOffsetAndLimitOrBuilder.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcQueryParam.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcQueryParamOrBuilder.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcQueryParamOuterClass.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcSealedEntity.java, evita_external_api/evita_external_api_grpc/shared/src/main/java/io/evitadb/externalApi/grpc/generated/GrpcTraversalMode.java, evita_functional_tests/src/test/java/io/evitadb/index/hierarchy/HierarchyIndexTest.java
This pull request fixes issue #839
* Added import for `EmptyFormula` in `ReferencePropertyTranslator.java` to handle cases where no nodes with parents are found.
* Updated the `getTraversedAndSortedReducedIndexPrimaryKeys` method to include parent nodes in the sorting process. This involved creating a new `UnaryOperator` to handle the sorting logic and applying it to the `referenceIndexIds`. [[1]](diffhunk://#diff-1dcb69e2627714b6d036cf9871629d27684c73427d31957be337d43165f237beR215-R251) [[2]](diffhunk://#diff-1dcb69e2627714b6d036cf9871629d27684c73427d31957be337d43165f237beL226-R267) [[3]](diffhunk://#diff-1dcb69e2627714b6d036cf9871629d27684c73427d31957be337d43165f237beL239-R280)
* Added a new method `listNodesIncludingParents` in `HierarchyIndex.java` to generate a bitmap that includes …
=> fix: Entities are not correctly sorted when hierarchyWithin filtering constraint is used

evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/utils/path/PathHandlingService.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/utils/path/routing/PathMatcher.java, evita_functional_tests/src/test/java/io/evitadb/server/EvitaServerTest.java
System API endpoints such as `/system/server-name` returns 404 error when access with trailing slash like so `/system/server-name/`.
This makes the API completely inaccessible on some server which do automatic redirect to trailing slash.
Refs: #746
=> feat: System endpoints return 404 with trailing slash

.github/workflows/ci-release.yml, evita_engine/src/main/java/io/evitadb/core/query/sort/attribute/translator/TraverseReferencePredecessorAttributeComparator.java
This pull request includes a change to the `TraverseReferencePredecessorAttributeComparator` class in the `evita_engine` module. The primary change involves modifying the comparison logic to handle potential null values for `sortedRecordsOffsets`.
Key change:
* [`evita_engine/src/main/java/io/evitadb/core/query/sort/attribute/translator/TraverseReferencePredecessorAttributeComparator.java`](diffhunk://#diff-5b8cb3a1d90d8c7fd54369bc49c339b9733a659661e473f5705cba77535f1895L141-R147): Updated the comparison logic to include a null check for `sortedRecordsOffsets` before attempting to access its elements.
=> Sorted records offsets must not be null error when ordering by non existing attribute data (#851)

evita_engine/src/main/java/io/evitadb/core/query/sort/attribute/translator/TraverseReferencePredecessorAttributeComparator.java, evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/configuration/GuiConfig.java, evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/gui/resolver/GuiHandler.java
This pull request includes several changes to the `evita_external_api_lab` module and a minor update to the `evita_engine` module. The primary focus is on enhancing the configuration and handling of GUI settings, as well as improving the asset serving and request handling in the GUI resolver.
Enhancements to GUI configuration:
* [`evita_external_api/evita_external_api_lab/src/main/java/io/evitadb/externalApi/lab/configuration/GuiConfig.java`](diffhunk://#diff-790709c9dce0e9e0d52f1aa1989b13d30178c8d23aa39153bd2e500766afd484L44-R115): Added new fields with appropriate getters, including `preferIncomingHostAndPort`, and updated constructors to handle these fields. Also added validation for preconfigured connections to check for duplicates. …
=> evitalab should prefer hostname and port of incoming request (#855)

evita_engine/src/main/java/io/evitadb/core/Evita.java, evita_engine/src/main/java/io/evitadb/core/EvitaInternalSessionContract.java, evita_engine/src/main/java/io/evitadb/core/EvitaSession.java, evita_engine/src/main/java/io/evitadb/core/SessionRegistry.java, evita_engine/src/main/java/io/evitadb/core/exception/SessionBusyException.java, evita_functional_tests/src/test/java/io/evitadb/api/EvitaReplacementFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/store/offsetIndex/model/StorageRecordTest.java
Catalog renaming/replacing/closing does not effectively prevent a new session from being created if there is a lot of traffic on the catalogue. Method close all sessions should enable some kind of flag that will prevent new session to pop-up. This flag needs to be reseted when the catalogue leaves critical section and starts to be available again. Or it needs to be removed from the catalogue listing much earlier.
I've written an integration test that uses 100 parallel clients doing 1000 queries and when 50% queries are finished I make the catalog replacement. This test now passes with zero query failures.
Refs: #850
=> fix: Session can be created during catalog replacement

evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultCatalogPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultEntityCollectionPersistenceService.java
This pull request focuses on improving logging and fixing a typo in the `evita_store` module. The most important changes include adding detailed logging for the compaction process and correcting a misspelled variable name.
Enhancements to logging:
* [`evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultCatalogPersistenceService.java`](diffhunk://#diff-3cfc78a9196f5b426470228b99c4b3448991e9c52bce692e65e41be138236dedL1379-R1389): Added detailed logging to provide information about the compaction process, including catalog name, entity collection type, file size, active record share, and disk consumption.
* [`evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultEntityCollectionPersistenceService.java`](diffhunk://#diff-2ad86126f5e5c85ab6a6c0061 …
=> chore: added logs before and after compaction

evita_engine/src/main/java/io/evitadb/core/query/filter/translator/facet/FacetHavingTranslator.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/resolver/constraint/FilterConstraintResolverTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/resolver/constraint/FilterConstraintResolverTest.java, evita_functional_tests/src/test/java/io/evitadb/test/client/query/FilterConstraintToJsonConverterTest.java, evita_query/src/main/java/io/evitadb/api/query/filter/FacetHaving.java
Unfortunatelly the [`includingChildren`](https://evitadb.io/documentation/query/filtering/references?lang=graphql#including-children) is wrapped into an and container by GraphQL API and is not evaluated correctly by the engine.
Refs: #862
=> fix: GraphQL query wraps facet includingChildren into and container

evita_api/src/main/java/io/evitadb/api/EvitaSessionContract.java, evita_engine/src/main/java/io/evitadb/core/EvitaSession.java, evita_external_api/evita_external_api_grpc/client/src/main/java/io/evitadb/driver/EvitaClientSession.java
When the commit behavior is used in following call:
```java
evita.updateCatalog(
"whatever",
session -> {
session.getEntity(...)
.orElseThrow()
.openForWrite()
.setAttribute("changed", OffsetDateTime.now())
.upsertVia(session);
},
TransactionContract.CommitBehavior.WAIT_FOR_WAL_PERSISTENCE
);
```
The default commit behavior WAIT_FOR_INDEX_PROPAGATION is still used.
Refs: #871
=> fix: Commit behavior passed as last argument of updateCatalog method is not respected

evita_engine/src/main/java/io/evitadb/core/Catalog.java, evita_engine/src/main/java/io/evitadb/core/Evita.java, evita_engine/src/main/java/io/evitadb/core/transaction/TransactionManager.java, evita_engine/src/main/java/io/evitadb/core/transaction/stage/AbstractTransactionStage.java, evita_engine/src/main/java/io/evitadb/core/transaction/stage/WalAppendingTransactionStage.java, evita_engine/src/main/java/io/evitadb/store/spi/CatalogPersistenceService.java, evita_store/evita_store_common/src/main/java/io/evitadb/store/exception/WriteAheadLogCorruptedException.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultCatalogPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/wal/CatalogWriteAheadLog.java
Under certain conditions (we are not yet sure which ones), the old WAL files, which are not written to, lack the tail statistics information in them. These statistics are used to locate transactions in them for the sake of the CDC, and also for replay in case evitaDB is restarted or transaction processing lags behind transaction commits.
The current handling is not secure enough and needs to be updated:
- when the catalogue is loaded, old WAL files need to be checked too (not just the current WAL file)
- if old WAL files lack tail information, they need to be checked, trimmed and the statistics appended to the tail
- all WAL files need to be checked to see if they contain consecutive monotonic rows of transactions
- Catalogue needs to be checked that the catalogue versions in: bootstrap …
=> fix: Old WAL files might not contain statistic tail written

evita_engine/src/main/java/io/evitadb/index/attribute/GlobalUniqueIndex.java
When GlobalUniqueIndex gets discarded it's responsible for discarding all changes in its internal transactional datastructures so that final transactional check doesn't find orphaned diff layers in memory. This is unfortunatelly done properly and `localeToIdIndex` + `idToLocaleIndex` is not removed in method `GlobalUniqueIndex`
Refs: #880
=> fix: Transactional maps are not correctly cleared when GlobalUniqueIndex is dropped

evita_functional_tests/src/test/java/io/evitadb/api/EvitaBackwardCompatibilityTest.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultCatalogPersistenceService.java, list-issues.sh
During upgrade check we've found out that the upgrade mechanism allows to write different catalog version to two spots in the files which are currently verified during catalog load and makes upgraded catalog as corrupted.
Refs: #883
=> fix: Upgrade script allows writing different catalog version to bootstrap record and catalog header

evita_functional_tests/src/test/java/io/evitadb/store/catalog/PostMortemAnalysisTest.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/kryo/ObservableInput.java
When compression enabled we randomly see problems like:
```
Unexpected record length - data probably corrupted (record should be long 24412B, but was read 16405B and another 16384B was requested for reading).
```
Refs: #887
=> fix: Error while decompressing data

documentation/user/en/use/api/example/manual-transaction-management.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/builder/constraint/ConstraintSchemaBuilder.java, evita_external_api/evita_external_api_core/src/main/java/io/evitadb/externalApi/api/catalog/dataApi/resolver/constraint/ConstraintDescriptorResolver.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/builder/constraint/GraphQLConstraintSchemaBuilder.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/resolver/constraint/FacetSummaryResolver.java, evita_external_api/evita_external_api_graphql/src/main/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/resolver/dataFetcher/QueryEntitiesDataFetcher.java, evita_functional_tests/src/test/java/io/evitadb/api/EvitaTransactionalFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/api/query/descriptor/ConstraintProcessorTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/CatalogGraphQLListEntitiesQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/graphql/api/catalog/dataApi/CatalogGraphQLQueryEntityQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/CatalogRestListEntitiesQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/externalApi/rest/api/catalog/dataApi/CatalogRestQueryEntityQueryFunctionalTest.java, evita_functional_tests/src/test/java/io/evitadb/store/catalog/PostMortemAnalysisTest.java, evita_functional_tests/src/test/java/io/evitadb/store/offsetIndex/OffsetIndexTest.java, evita_functional_tests/src/test/java/io/evitadb/utils/FileUtilsTest.java, evita_functional_tests/src/test/resources/META-INF/documentation/imports.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintDescriptor.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintDescriptorProvider.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/ConstraintProcessor.java, evita_query/src/main/java/io/evitadb/api/query/descriptor/annotation/ConstraintSupportedValues.java, evita_query/src/main/java/io/evitadb/api/query/order/AttributeNatural.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/OffsetIndex.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/OffsetIndexDescriptor.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/OffsetIndexSerializationService.java, evita_store/evita_store_key_value/src/main/java/io/evitadb/store/offsetIndex/io/OffHeapMemoryOutputStream.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/CatalogOffsetIndexStoragePartPersistenceService.java, evita_store/evita_store_server/src/main/java/io/evitadb/store/catalog/DefaultEntityCollectionPersistenceService.java
This pull request introduces several enhancements and fixes across multiple files, focusing on improving functionality related to schema constraints, adding new tests, and refining code quality. Key changes include the addition of support for sortable attribute compound schemas, a new long-running test for file rotation and compaction, and minor code adjustments for clarity and compliance.
- cannot sort by sortable attribute compounds in GQL and REST APIs (984)[https://github.com/FgForrest/evitaDB/issues/894]
- prevention of pointers outside file, minor fixes for edge cases
* [`ConstraintSchemaBuilder.java`](diffhunk://#diff-a94afc1e85fb747226578ba687873abe99775dd8dff9cbebe6bdc2fdfac94ec0R433-R459): Added support for sortable attribute compound schemas, enabling dynamic classifiers and …
=> Hotfix release
